name: "road_vision"

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"

  fake_agent:
    container_name: agent
    build: .
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "agent_data_topic"
      DELAY: 1